FROM node:18-alpine

ENV VITE_API_URL 'http://localhost:8000'
WORKDIR /app

RUN cd /app

COPY package.json ./

RUN yarn install

COPY . .

EXPOSE 3000

CMD ["yarn", "dev", "--host", "0.0.0.0", "--port", "3000"] 