version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fastapi-backend-prod
    ports:
      - "8000:8000"
    restart: always
    networks:
      - app-network
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build: ./frontend
    container_name: react-frontend-prod
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 